# Generated by Django 4.1.3 on 2022-12-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0002_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
