# Generated by Django 4.1.3 on 2022-11-28 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0002_ingredient_remove_recipeingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='myCookbook/static/myCookbook/images/default_profile.png', upload_to='myCookbook/static/myCookbook/recipe', verbose_name='Recipe Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_recipes_posted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_recipes_saved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='myCookbook/static/myCookbook/profile/default_profile.png', upload_to='myCookbook/static/myCookbook/profile', verbose_name='Profile Image'),
        ),
    ]
