# Generated by Django 4.1.3 on 2022-11-28 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0003_recipe_image_alter_user_num_recipes_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_recipes_posted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_recipes_saved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Servings'),
        ),
    ]
