# Generated by Django 4.1.3 on 2022-12-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
