# Generated by Django 4.1.3 on 2022-11-28 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0004_alter_user_num_recipes_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myCookbook.recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('Lbs', 'Pounds'), ('Oz', 'Ounces'), ('C', 'Cups'), ('Tb', 'Tablespoon'), ('Ts', 'Teaspoon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='num_servings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
