# Generated by Django 4.1.3 on 2022-12-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0007_recipe_insturctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='insturctions',
            new_name='instructions',
        ),
    ]
