# Generated by Django 4.1.3 on 2022-12-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0009_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='myCookbook/images/recipeImages/defaultImage.jpeg', upload_to='myCookbook/images/recipeImages', verbose_name='Recipe Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='myCookbook/images/profileImages/default_profile.png', upload_to='myCookbook/images/profileImages', verbose_name='Profile Image'),
        ),
    ]
