# Generated by Django 4.1.3 on 2022-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0010_alter_recipe_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profileImages/default_profile.png', upload_to='images/profileImages', verbose_name='Profile Image'),
        ),
    ]
