# Generated by Django 4.1.3 on 2022-12-04 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0014_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('NA', 'NA'), ('Lbs', 'Pounds'), ('Oz', 'Ounces'), ('C', 'Cups'), ('Tb', 'Tablespoon'), ('Ts', 'Teaspoon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_recipes_posted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Recipes Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_recipes_saved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Recipes Saved'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='myCookbook/images/recipeImages/default_profile.png', null=True, upload_to='myCookbook/images/recipeImages', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myCookbook.category'),
        ),
    ]
