# Generated by Django 4.1.3 on 2022-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0015_category_alter_ingredient_units_alter_recipe_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Categories'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
