# Generated by Django 4.1.3 on 2022-12-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0016_alter_category_name_delete_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, to='myCookbook.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
