# Generated by Django 4.1.3 on 2022-12-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0019_recipe_slug_alter_recipe_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
