# Generated by Django 4.1.3 on 2022-12-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCookbook', '0021_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
